modules:
  - name: terraform-gcs-remote-state-bootstrap
    type: github
    repo: datasciencecampus/terraform-gcs-remote-state-bootstrap
    lookup: release
    pin: tag
    glob: terraform/**/*.tf
    source_prefix: git::https://github.com/datasciencecampus/terraform-gcs-remote-state-bootstrap.git?ref=

  - name: terraform-google-network
    type: registry
    source: terraform-google-modules/network/google
    file: terraform/main.tf