name: Update Terraform module versions

on:
  # schedule:
  #   - cron: "0 6 * * 1" # 6am Monday
  workflow_dispatch:
    inputs:
      manifest_path:
        description: "Path to manifest file in this repository"  
        required: false
        default: .github/module-update-manifest.yml
        type: string

permissions:
  contents: write
  pull-requests: write

jobs:
  update-modules:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: "3.12"

      - name: Set up Terraform
        uses: hashicorp/setup-terraform@v3

      - name: Install package
        run: |
          python -m pip install --upgrade pip
          pip install .

      - name: Run module update script
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        run: |
          update-tf-modules --manifest-path "${{ inputs.manifest_path }}"

      - name:  Show changed files
        run: |
          git status --short
          git diff --stat
          git diff -- terraform

      - name: Check Terraform formatting
        run: |
          terraform fmt -check -recursive terraform

      - name: Create pull request
        uses: peter-evans/create-pull-request@v6
        with:
          commit-message: "chore(update-tf-modules): update Terraform module versions"
          title: Update Terraform module versions
          body: |
            Automated update of Terraform module versions.
          branch: automation/update-terraform-modules
          base: main
          delete-branch: true
          add-paths: |
            terraform/**/*.tf